[space]
xmin = 0.0
xmax = 0.05
dx = 0.0004
ymin = 0.0
ymax = 0.01
dy = 0.00004

[time]
t0 = 0.0
tfinal = 100.0
dt = 0.1
# ExplicitEuler = Explicit Euler, ImplicitEuler = Implicit Euler
scheme = "ImplicitEuler"

[other]
lambdapv =1.0
ppv = 1500.0
cpv= 1000.0
results = "results"
